# Generated by Django 3.1.3 on 2021-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FilePathField(default='', path='C:\\Users\\hp\\Desktop\\Software engineering\\level4-Django\\Portfolio-website-using-django\\myportfolio/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='C:\\Users\\hp\\Desktop\\Software engineering\\level4-Django\\Portfolio-website-using-django\\myportfolio/static/img'),
        ),
    ]
